<a href="https://colab.research.google.com/github/navid-nowroz/Enigma/blob/main/extras/exercises/00_pytorch_fundamentals_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [1]:
# Import torch
import torch

# Create random tensor
tensor = torch.rand(7, 7)
tensor


tensor([[0.3360, 0.3863, 0.5551, 0.0941, 0.4646, 0.3027, 0.9976],
        [0.2162, 0.3341, 0.4043, 0.4658, 0.5336, 0.4064, 0.0408],
        [0.6841, 0.3934, 0.7334, 0.5038, 0.3543, 0.2041, 0.2111],
        [0.7148, 0.6924, 0.4843, 0.6286, 0.0586, 0.2150, 0.8050],
        [0.5360, 0.6717, 0.3369, 0.1249, 0.6241, 0.7039, 0.6812],
        [0.7908, 0.4099, 0.9946, 0.1762, 0.4999, 0.2313, 0.8037],
        [0.9552, 0.8327, 0.1021, 0.8782, 0.9104, 0.4249, 0.3826]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [2]:
# Create another random tensor
tensor2 = torch.rand(1, 7)
# Perform matrix multiplication
mul_tensor = torch.matmul(tensor, tensor2.T)
mul_tensor

tensor([[1.7114],
        [1.5459],
        [1.8062],
        [1.9013],
        [2.2909],
        [2.2009],
        [2.4936]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [4]:
# Set manual seed
torch.manual_seed(0)

# Create two random tensors
tensor_A = torch.rand(7, 7)
tensor_B = torch.rand(1, 7)

# Matrix multiply tensors
mul_tensors = torch.matmul(tensor_A, tensor_B.T)
mul_tensors, mul_tensors.size()

(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]),
 torch.Size([7, 1]))

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [9]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [10]:
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
device = "cuda" if torch.cuda.is_available() else "cpu"
# Create two random tensors on GPU
gpu_tensor_A = torch.rand(2, 3, device = device)
gpu_tensor_B = torch.rand(2, 3, device = device)

print(device)
print(gpu_tensor_A)
print(gpu_tensor_B)

cuda
tensor([[0.1272, 0.8167, 0.5440],
        [0.6601, 0.2721, 0.9737]], device='cuda:0')
tensor([[0.6208, 0.0276, 0.3255],
        [0.1114, 0.6812, 0.3608]], device='cuda:0')



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [14]:
# Perform matmul on tensor_A and tensor_B
gpu_mul_tensors = torch.matmul(gpu_tensor_A, gpu_tensor_B.T)
gpu_mul_tensors, gpu_mul_tensors.shape

(tensor([[0.2786, 0.7668],
         [0.7343, 0.6102]], device='cuda:0'),
 torch.Size([2, 2]))

### 8. Find the maximum and minimum values of the output of 7.

In [15]:
# Find max
print(gpu_mul_tensors.max())
# Find min
print(gpu_mul_tensors.min())


tensor(0.7668, device='cuda:0')
tensor(0.2786, device='cuda:0')


### 9. Find the maximum and minimum index values of the output of 7.

In [16]:
# Find arg max
print(gpu_mul_tensors.argmax())

# Find arg min
print(gpu_mul_tensors.argmin())


tensor(1, device='cuda:0')
tensor(0, device='cuda:0')



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [18]:
# Set seed
import torch
torch.manual_seed(7)

# Create random tensor
tensor = torch.rand(1,1,1, 10)

# Remove single dimensions
small_tensor = tensor.squeeze()

# Print out tensors and their shapes
print(tensor, tensor.shape)
print(small_tensor, small_tensor.shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
